### ISSUE TITLE
Erhöhen der Session Lifetime

### ISSUE THREAD

**Issue by shaaati** [DigiTrace/AM-System#34]
Aktuell muss man sich im Tagesverlauf mehrmals neu am System anmelden (Session Lifetime sowas wie 2h?).

Ich schlage vor, dass die lifetime erhöht wird, sodass nur eine Anmeldung pro Arbeitstag erforderlich ist (ca. 10-12h Session Lifetime).

**Comment by EinType** [comment]
Bezüglich des Sessions Timeouts bzw. der Problematik, dass man sich zu häufig Anmelden muss, sind folgende zwei Punkte zu beachten:

1. Die Webanwendung setzt typischerweise einen Cookie ein, welcher kein Expiry Date hat, also sich die Gültigkeit an der Aktivität des Benutzers orientiert (Thema: Garbage Collection). Das die Gültigkeit mit der letzten Aktion des Benutzer verlängert wird, pass meiner Ansicht so. Um die maximale Dauer (welche zudem PHP auch eine Wahrscheinlichkeit vorsetzt) zu erhöhen, muss die Änderung nicht auf Anwendungsebene, sondern in der PHP Konfiguration realisiert werden.
2. Die Webanwendung besitzt eine "remember me" Funktionalität, wo serverseitig ein dedizierter Cookie gesetzt wird, welcher 7 Tage lang gültig ist. Mit diesem Token sollte das mehrfache Anmelden am AM-System unterbunden werden, wenn es einen konkret stört. 

Ich sehe anhand der äußeren Konfiguration möglicherweise den Bedarf, in der Adminoberfläche eine Art Statusseite zu implementieren, wo PHP und Anwendungsspezifische Parameter zur Kontrolle ausgegeben werden, um im Beispiel einer Änderung der PHP Version mögliche offene Konfigrationsparameter nachjustieren zu können (außerhalb der Anwendung).
