### ISSUE TITLE
Editieren eines (Datenträger-)Objekts aktualisiert nicht den Abschnitt "Zusätliche Informationen"

### ISSUE THREAD

**Issue by shaaati** [DigiTrace/AM-System#6]
Bei Datenträgern (Asservaten und firmeninternen Datenträgern) gibt es spezielle Zusatzinformationen, etwa Bauart, Größe, Seriennummer, ...
Wird ein solches Objekt editiert und z.B. die Seriennummer geändert, zeigt die Anwendung eine Erfolgsmeldung. Tatsächlich erfolgt aber kein Update der erweiterten Informationen und es erscheint auch kein Eintrag in der Objekthistorie.

**Comment by EinType** [comment]
Habe dieses Verhalten auf der aktuellen Version der Software getestet, hierbei scheinen die Datenwerte akkurat und protokolliert verändert zu werden. Möglicherweise hatte die Anwendung zum Zeitpunkt des Issues diesen Fehler. Schließe das Issue
